services:

  ###> symfony/php ###
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"   # Expose le serveur PHP sur le port 8080
    volumes:
      - .:/var/www # Montage du dossier de l'application
      - ./var/log:/var/www/var/log # Montage des logs
      - ./var/cache:/var/www/var/cache # Montage du cache
    environment:
      SYMFONY_ENV: dev # Environnement de développement pour docker
    depends_on: # Dépendances des services
      - database # mysql (SQL)
      - mongodb # mongo (NoSQL)
    networks:
      - zoo  # Réseau pour communiquer avec les autres services

  ###< symfony/php ###

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0 # Version de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zooarcadia
    ports:
      - "3307:3306" # Expose le serveur MySQL sur le port 3307
    volumes:
      - database_data:/var/lib/mysql:rw # Volume pour les données de la base de données
    networks:
      - zoo
  ###< doctrine/doctrine-bundle ###

  ###> doctrine/mongodb-odm-bundle ###
  mongodb:
    image: mongo:6.0 # Version de MongoDB
    container_name: mongodb_local # Nom du conteneur
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: password 
      MONGO_INITDB_DATABASE: symfony 
    ports:
      - "27017:27017" # Expose le service MongoDB sur le port 27017
    volumes:
      - mongo_data:/data/db # Volume pour les données de MongoDB
      - ./scripts/nosql.js:/docker-entrypoint-initdb.d/nosql.js # Lancement de scripts automatiques
    networks:
      - zoo
  ###< doctrine/mongodb-odm-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - zoo
  ###< symfony/mailer ###



volumes:
  database_data:
  mongo_data:

networks:
  zoo:
    driver: bridge